POST http://localhost:3005/api/user/friends/672652ef129210b553d24af0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9uX2hhdmwiLCJpZCI6IjY3MjY1NDZkNmYzMTU2NDIxYTcyZmQ3ZCIsImlhdCI6MTczMDU5MjA3Mn0.a6cf1l_EzHc62P4Y76mFY85Swn_FuC_HIyCdzyE4EXc