DELETE http://localhost:3005/api/exercise/672675717297e2ebdec9b62b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9uX2hhdmwiLCJpZCI6IjY3MjY1NDZkNmYzMTU2NDIxYTcyZmQ3ZCIsImlhdCI6MTczMDYzNzI3MH0.7beZVhq1-f0j7rjZrvNqWhKISYlJXXaZHZumHv5Z8Hg