DELETE http://localhost:3005/api/exercise/672666579cb3c63ada3bf754
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9uX2hhdmwiLCJpZCI6IjY3MjY1NDZkNmYzMTU2NDIxYTcyZmQ3ZCIsImlhdCI6MTczMDU3Mjk4MH0.arPt0YQfgDwHF8K5Kbl8jRL0GwFfr5YzR6i0opvn_5s