POST http://localhost:3005/api/food
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9uX2hhdmwiLCJpZCI6IjY3MjY1NDZkNmYzMTU2NDIxYTcyZmQ3ZCIsImlhdCI6MTczMDY1MjU3N30.ptsI5pNEiOiTOcgbkDhwpLzDnURrT3J8KKVXojoCtWA

{
    "name" : "apple",
    "size" : 200,
    "date": "2024-11-05"
}
